/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/": {
    get: {
      responses: {
        /** OK */
        200: unknown;
      };
    };
  };
  "/migrations": {
    get: {
      parameters: {
        query: {
          id?: parameters["rowFilter.migrations.id"];
          name?: parameters["rowFilter.migrations.name"];
          created_at?: parameters["rowFilter.migrations.created_at"];
          /** Filtering Columns */
          select?: parameters["select"];
          /** Ordering */
          order?: parameters["order"];
          /** Limiting and Pagination */
          offset?: parameters["offset"];
          /** Limiting and Pagination */
          limit?: parameters["limit"];
        };
        header: {
          /** Limiting and Pagination */
          Range?: parameters["range"];
          /** Limiting and Pagination */
          "Range-Unit"?: parameters["rangeUnit"];
          /** Preference */
          Prefer?: parameters["preferCount"];
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["migrations"][];
        };
        /** Partial Content */
        206: unknown;
      };
    };
    post: {
      parameters: {
        body: {
          /** migrations */
          migrations?: definitions["migrations"];
        };
        query: {
          /** Filtering Columns */
          select?: parameters["select"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** Created */
        201: unknown;
      };
    };
    delete: {
      parameters: {
        query: {
          id?: parameters["rowFilter.migrations.id"];
          name?: parameters["rowFilter.migrations.name"];
          created_at?: parameters["rowFilter.migrations.created_at"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
    patch: {
      parameters: {
        query: {
          id?: parameters["rowFilter.migrations.id"];
          name?: parameters["rowFilter.migrations.name"];
          created_at?: parameters["rowFilter.migrations.created_at"];
        };
        body: {
          /** migrations */
          migrations?: definitions["migrations"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
  };
  "/profiles": {
    get: {
      parameters: {
        query: {
          id?: parameters["rowFilter.profiles.id"];
          full_name?: parameters["rowFilter.profiles.full_name"];
          is_admin?: parameters["rowFilter.profiles.is_admin"];
          created_at?: parameters["rowFilter.profiles.created_at"];
          updated_at?: parameters["rowFilter.profiles.updated_at"];
          /** Filtering Columns */
          select?: parameters["select"];
          /** Ordering */
          order?: parameters["order"];
          /** Limiting and Pagination */
          offset?: parameters["offset"];
          /** Limiting and Pagination */
          limit?: parameters["limit"];
        };
        header: {
          /** Limiting and Pagination */
          Range?: parameters["range"];
          /** Limiting and Pagination */
          "Range-Unit"?: parameters["rangeUnit"];
          /** Preference */
          Prefer?: parameters["preferCount"];
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["profiles"][];
        };
        /** Partial Content */
        206: unknown;
      };
    };
    post: {
      parameters: {
        body: {
          /** profiles */
          profiles?: definitions["profiles"];
        };
        query: {
          /** Filtering Columns */
          select?: parameters["select"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** Created */
        201: unknown;
      };
    };
    delete: {
      parameters: {
        query: {
          id?: parameters["rowFilter.profiles.id"];
          full_name?: parameters["rowFilter.profiles.full_name"];
          is_admin?: parameters["rowFilter.profiles.is_admin"];
          created_at?: parameters["rowFilter.profiles.created_at"];
          updated_at?: parameters["rowFilter.profiles.updated_at"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
    patch: {
      parameters: {
        query: {
          id?: parameters["rowFilter.profiles.id"];
          full_name?: parameters["rowFilter.profiles.full_name"];
          is_admin?: parameters["rowFilter.profiles.is_admin"];
          created_at?: parameters["rowFilter.profiles.created_at"];
          updated_at?: parameters["rowFilter.profiles.updated_at"];
        };
        body: {
          /** profiles */
          profiles?: definitions["profiles"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
  };
  "/waiting_list": {
    get: {
      parameters: {
        query: {
          id?: parameters["rowFilter.waiting_list.id"];
          full_name?: parameters["rowFilter.waiting_list.full_name"];
          email?: parameters["rowFilter.waiting_list.email"];
          email_confirmed_at?: parameters["rowFilter.waiting_list.email_confirmed_at"];
          invited_at?: parameters["rowFilter.waiting_list.invited_at"];
          created_at?: parameters["rowFilter.waiting_list.created_at"];
          updated_at?: parameters["rowFilter.waiting_list.updated_at"];
          /** Filtering Columns */
          select?: parameters["select"];
          /** Ordering */
          order?: parameters["order"];
          /** Limiting and Pagination */
          offset?: parameters["offset"];
          /** Limiting and Pagination */
          limit?: parameters["limit"];
        };
        header: {
          /** Limiting and Pagination */
          Range?: parameters["range"];
          /** Limiting and Pagination */
          "Range-Unit"?: parameters["rangeUnit"];
          /** Preference */
          Prefer?: parameters["preferCount"];
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["waiting_list"][];
        };
        /** Partial Content */
        206: unknown;
      };
    };
    post: {
      parameters: {
        body: {
          /** waiting_list */
          waiting_list?: definitions["waiting_list"];
        };
        query: {
          /** Filtering Columns */
          select?: parameters["select"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** Created */
        201: unknown;
      };
    };
    delete: {
      parameters: {
        query: {
          id?: parameters["rowFilter.waiting_list.id"];
          full_name?: parameters["rowFilter.waiting_list.full_name"];
          email?: parameters["rowFilter.waiting_list.email"];
          email_confirmed_at?: parameters["rowFilter.waiting_list.email_confirmed_at"];
          invited_at?: parameters["rowFilter.waiting_list.invited_at"];
          created_at?: parameters["rowFilter.waiting_list.created_at"];
          updated_at?: parameters["rowFilter.waiting_list.updated_at"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
    patch: {
      parameters: {
        query: {
          id?: parameters["rowFilter.waiting_list.id"];
          full_name?: parameters["rowFilter.waiting_list.full_name"];
          email?: parameters["rowFilter.waiting_list.email"];
          email_confirmed_at?: parameters["rowFilter.waiting_list.email_confirmed_at"];
          invited_at?: parameters["rowFilter.waiting_list.invited_at"];
          created_at?: parameters["rowFilter.waiting_list.created_at"];
          updated_at?: parameters["rowFilter.waiting_list.updated_at"];
        };
        body: {
          /** waiting_list */
          waiting_list?: definitions["waiting_list"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
  };
  "/rpc/is_admin": {
    post: {
      parameters: {
        body: {
          args: {
            /** Format: uuid */
            user_id: string;
          };
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferParams"];
        };
      };
      responses: {
        /** OK */
        200: unknown;
      };
    };
  };
}

export interface definitions {
  migrations: {
    /**
     * Format: integer
     * @description Note:
     * This is a Primary Key.<pk/>
     */
    id: number;
    /** Format: character varying */
    name: string;
    /** Format: timestamp without time zone */
    created_at: string;
  };
  profiles: {
    /**
     * Format: uuid
     * @description Note:
     * This is a Primary Key.<pk/>
     */
    id: string;
    /** Format: character varying */
    full_name?: string;
    /**
     * Format: boolean
     * @default false
     */
    is_admin?: boolean;
    /**
     * Format: timestamp with time zone
     * @default now()
     */
    created_at: string;
    /** Format: timestamp with time zone */
    updated_at?: string;
  };
  waiting_list: {
    /**
     * Format: uuid
     * @description Note:
     * This is a Primary Key.<pk/>
     * @default extensions.uuid_generate_v4()
     */
    id: string;
    /** Format: character varying */
    full_name: string;
    /** Format: character varying */
    email: string;
    /** Format: timestamp with time zone */
    email_confirmed_at?: string;
    /** Format: timestamp with time zone */
    invited_at?: string;
    /**
     * Format: timestamp with time zone
     * @default now()
     */
    created_at: string;
    /** Format: timestamp with time zone */
    updated_at?: string;
  };
}

export interface parameters {
  /**
   * @description Preference
   * @enum {string}
   */
  preferParams: "params=single-object";
  /**
   * @description Preference
   * @enum {string}
   */
  preferReturn: "return=representation" | "return=minimal" | "return=none";
  /**
   * @description Preference
   * @enum {string}
   */
  preferCount: "count=none";
  /** @description Filtering Columns */
  select: string;
  /** @description On Conflict */
  on_conflict: string;
  /** @description Ordering */
  order: string;
  /** @description Limiting and Pagination */
  range: string;
  /**
   * @description Limiting and Pagination
   * @default items
   */
  rangeUnit: string;
  /** @description Limiting and Pagination */
  offset: string;
  /** @description Limiting and Pagination */
  limit: string;
  /** @description migrations */
  "body.migrations": definitions["migrations"];
  /** Format: integer */
  "rowFilter.migrations.id": string;
  /** Format: character varying */
  "rowFilter.migrations.name": string;
  /** Format: timestamp without time zone */
  "rowFilter.migrations.created_at": string;
  /** @description profiles */
  "body.profiles": definitions["profiles"];
  /** Format: uuid */
  "rowFilter.profiles.id": string;
  /** Format: character varying */
  "rowFilter.profiles.full_name": string;
  /** Format: boolean */
  "rowFilter.profiles.is_admin": string;
  /** Format: timestamp with time zone */
  "rowFilter.profiles.created_at": string;
  /** Format: timestamp with time zone */
  "rowFilter.profiles.updated_at": string;
  /** @description waiting_list */
  "body.waiting_list": definitions["waiting_list"];
  /** Format: uuid */
  "rowFilter.waiting_list.id": string;
  /** Format: character varying */
  "rowFilter.waiting_list.full_name": string;
  /** Format: character varying */
  "rowFilter.waiting_list.email": string;
  /** Format: timestamp with time zone */
  "rowFilter.waiting_list.email_confirmed_at": string;
  /** Format: timestamp with time zone */
  "rowFilter.waiting_list.invited_at": string;
  /** Format: timestamp with time zone */
  "rowFilter.waiting_list.created_at": string;
  /** Format: timestamp with time zone */
  "rowFilter.waiting_list.updated_at": string;
}

export interface operations {}

export interface external {}
