version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        PUBLIC_SUPABASE_URL:
        PUBLIC_SUPABASE_ANON_KEY:
        SUPABASE_SERVICE_ROLE_KEY:
    ports:
      - 80:3000
    volumes:
      - ./build:/app/build/
