name: Fly deploy
on:
  push:
    branches:
      - main

jobs:
  database-migration:
    name: Database migration
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    env:
      CONNECTION_STRING: ${{ secrets.CONNECTION_STRING }}
    steps:
      - name: Checkout app
        uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        run: npm install -g pnpm && pnpm i

      - name: Check migration status
        run: pnpm m:status

      - name: Run migration
        run: pnpm m:up

  deploy:
    name: Deploy app
    runs-on: ubuntu-latest
    steps:
      - name: Checkout app
        uses: actions/checkout@v2

      - name: Deploy app
        uses: superfly/flyctl-actions@1.1
        with:
          args: 'deploy
            --no-cache
            --local-only
            --detach
            --build-arg VITE_SUPABASE_URL=${{ secrets.VITE_SUPABASE_URL }}
            --build-arg VITE_SUPABASE_ANON_KEY=${{ secrets.VITE_SUPABASE_ANON_KEY }}
            --build-arg SUPABASE_SERVICE_ROLE_KEY=${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}
            --build-arg VITE_APP_URL=${{ secrets.VITE_APP_URL }}'
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
